site_name: Thesis Documentation
site_url: https://mirrorstudios.github.io/fallernetes-documentation/
theme:
  name: material
  features:
    - content.code.copy
    - content.mode.select
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Server: server.md
  - Fleet: fleet.md
  - GameType: gametype.md
  - Autoscaler: autoscaler.md
  - Sidecar: sidecar.md
  - Service: service.md
  - Getting Started: started.md